Feat/pfm issue 10674 generate company wide release notes
collaborationFactory/cplace-npm-tools pull request #98
Opened 2022-09-19 15:24 UTC by stefancplace

2022-09-28 13:46 UTC, stefancplace commented
to be tested:
-> generated changelog did not change
-> commands used for orbs still working

2022-09-28 14:25 UTC, Kaltenbach requested changes
Please also move src/test to the new test folder 😄

2022-09-28 14:25 UTC, Kaltenbach commented on src/commands/release-notes/GenerateReleaseNotes.ts
> +                Global.isVerbose() && console.log(`to commit has hash ${this.toHash}`);
```suggestion
                Global.isVerbose() && console.log(`--to commit has hash ${this.toHash}`);
```

2022-09-28 14:25 UTC, Kaltenbach commented on src/commands/release-notes/GenerateReleaseNotes.ts
> +        this.changelog = [`_Changelog created on ${new Date().toDateString()}_`];
Please check format for backwards-compatibility with the html we publish to central.
[release notes example in central](https://central.collaboration-factory.de/pages/yglclatbg0lps2xgqbfurr778/22.4?highlightedEntityUid=page%2Fyglclatbg0lps2xgqbfurr778),
See also [the script in the cplace orb](https://github.com/collaborationFactory/cplace-circleci-orb/blob/master/src/scripts/publish_release_notes.sh).

2022-09-28 19:47 UTC, stefancplace commented
compared CHANGELOG.md of @cplace/cli@0.19.12 with this PR

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/49144956/192874768-03dee0e7-3e04-4945-a258-219a7834ab56.png">

2022-09-29 06:39 UTC, slaven3kopic approved these changes
Nice

2022-09-29 07:34 UTC, Kaltenbach approved these changes
Fine for me.

2022-09-29 07:34 UTC, Kaltenbach approved these changes

2022-09-29 07:36 UTC, Kaltenbach commented
One thing about the test folder refactoring:
<img width="137" alt="Bildschirmfoto 2022-09-29 um 09 33 48" src="https://user-images.githubusercontent.com/36501371/192969136-80ef0f81-a49e-44ba-9c6f-92abf62e02ae.png">

There are still the two test folders. Is this by intention @stefancplace? Else this should be fixed in a further PR to not block this one. 😄

2022-09-29 07:38 UTC, stefancplace commented
I don`t have the folder locally, is there any files in there? @Kaltenbach 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/49144956/192969769-ed75d8b7-dfa0-443e-ae9b-3519ef8e5567.png">

2022-09-29 07:52 UTC, Kaltenbach commented
Strange, why... the screenshot if from the PR's website...
<img width="325" alt="Bildschirmfoto 2022-09-29 um 09 51 16" src="https://user-images.githubusercontent.com/36501371/192972916-44174157-fefc-4d9d-9654-1cbea6bc6aae.png">

2022-09-29 08:00 UTC, stefancplace commented
I understand that the picture indicates that `src/test/flow/ReleaseNumber.test.ts` and  `src/test/helpers/idea.ts` have been deleted and are now under `test/flow/ReleaseNumber.test.ts` and `test/helpers/idea.ts` .

2022-09-29 08:18 UTC, Kaltenbach commented
> I understand that 

right 🙈 
sorry 😂

2022-09-29 09:36 UTC, merged